### ISSUE TITLE
Docker image build completes with errors but does not run due to these errors

### ISSUE THREAD

**Issue by grav3m1nd-byte** [codingo/NoSQLMap#131]
## What's the problem (or question)?

Given that the normal install fails as this project is still on Python2, docker was a good option but the image build completes with errors and does not run.

## Do you have an idea for a solution?

Probably the issue would be resolved by switching all the dependencies to use Python3 and the needed components listed in the setup.py, which relying on their latest versions.

## How can we reproduce the issue?

Specific to the docker build:

1. Run `sudo docker build -t nosqlmap .`
2. Watch for the output
```
┌──(kali 👿 kali)-[/opt/…/docker]
└─$ sudo docker build -t nosqlmap .                                                                      (master|✔)
Sending build context to Docker daemon  4.096kB
Step 1/10 : FROM python:2.7-alpine
2.7-alpine: Pulling from library/python
aad63a933944: Pull complete 
259d822268fb: Pull complete 
10ba96d218d3: Pull complete 
44ba9f6a4209: Pull complete 
Digest: sha256:724d0540eb56ffaa6dd770aa13c3bc7dfc829dec561d87cb36b2f5b9ff8a760a
Status: Downloaded newer image for python:2.7-alpine
 ---> 8579e446340f
Step 2/10 : RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.9/main' >> /etc/apk/repositories
 ---> Running in c21727028e52
Removing intermediate container c21727028e52
 ---> b79d83f82cb7
Step 3/10 : RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.9/community' >> /etc/apk/repositories
 ---> Running in d3b040b695a0
Removing intermediate container d3b040b695a0
 ---> 7f781ebf5db6
Step 4/10 : RUN apk update && apk add mongodb git
 ---> Running in c8c13f4a518f
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
v3.11.13-12-g2cfa91a2b4 [http://dl-cdn.alpinelinux.org/alpine/v3.11/main]
v3.11.11-124-gf2729ece5a [http://dl-cdn.alpinelinux.org/alpine/v3.11/community]
v3.9.6-143-ga5f34edab6 [http://dl-cdn.alpinelinux.org/alpine/v3.9/main]
v3.9.6-138-ge069a77b3b [http://dl-cdn.alpinelinux.org/alpine/v3.9/community]
OK: 21064 distinct packages available
(1/17) Installing nghttp2-libs (1.40.0-r1)
(2/17) Installing libcurl (7.79.1-r0)
(3/17) Installing pcre2 (10.34-r1)
(4/17) Installing git (2.24.4-r0)
(5/17) Installing boost-system (1.67.0-r2)
(6/17) Installing libgcc (9.3.0-r0)
(7/17) Installing boost-filesystem (1.67.0-r2)
(8/17) Installing boost-iostreams (1.67.0-r2)
(9/17) Installing boost-program_options (1.67.0-r2)
(10/17) Installing pcre (8.43-r1)
(11/17) Installing libstdc++ (9.3.0-r0)
(12/17) Installing libpcrecpp (8.43-r1)
(13/17) Installing db (5.3.28-r1)
(14/17) Installing libsasl (2.1.27-r5)
(15/17) Installing snappy (1.1.7-r1)
(16/17) Installing yaml-cpp (0.6.3-r0)
(17/17) Installing mongodb (4.0.5-r0)
Executing mongodb-4.0.5-r0.pre-install
Executing busybox-1.31.1-r9.trigger
OK: 138 MiB in 49 packages
Removing intermediate container c8c13f4a518f
 ---> 6c5374fc937d
Step 5/10 : RUN git clone https://github.com/codingo/NoSQLMap.git /root/NoSqlMap
 ---> Running in b81683293233
Cloning into '/root/NoSqlMap'...
Removing intermediate container b81683293233
 ---> 16cd6af4d287
Step 6/10 : WORKDIR /root/NoSqlMap
 ---> Running in 9faf8ca11e73
Removing intermediate container 9faf8ca11e73
 ---> 3d2af3679a71
Step 7/10 : RUN python setup.py install
 ---> Running in c2a5e08e5211
running install
running bdist_egg
running egg_info
creating NoSQLMap.egg-info
writing requirements to NoSQLMap.egg-info/requires.txt
writing NoSQLMap.egg-info/PKG-INFO
writing top-level names to NoSQLMap.egg-info/top_level.txt
writing dependency_links to NoSQLMap.egg-info/dependency_links.txt
writing entry points to NoSQLMap.egg-info/entry_points.txt
writing manifest file 'NoSQLMap.egg-info/SOURCES.txt'
reading manifest file 'NoSQLMap.egg-info/SOURCES.txt'
writing manifest file 'NoSQLMap.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
creating build
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

running install_scripts
running build_scripts
creating build/scripts-2.7
copying and adjusting nosqlmap.py -> build/scripts-2.7
copying and adjusting nsmmongo.py -> build/scripts-2.7
copying and adjusting nsmcouch.py -> build/scripts-2.7
copying and adjusting nsmscan.py -> build/scripts-2.7
copying and adjusting nsmweb.py -> build/scripts-2.7
copying and adjusting exception.py -> build/scripts-2.7
changing mode of build/scripts-2.7/nosqlmap.py from 644 to 755
changing mode of build/scripts-2.7/nsmmongo.py from 644 to 755
changing mode of build/scripts-2.7/nsmcouch.py from 644 to 755
changing mode of build/scripts-2.7/nsmscan.py from 644 to 755
changing mode of build/scripts-2.7/nsmweb.py from 644 to 755
changing mode of build/scripts-2.7/exception.py from 644 to 755
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/nsmmongo.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/nosqlmap.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/nsmcouch.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/exception.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/nsmscan.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/nsmweb.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/nsmmongo.py to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/nosqlmap.py to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/nsmcouch.py to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/exception.py to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/nsmscan.py to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/nsmweb.py to 755
copying NoSQLMap.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying NoSQLMap.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying NoSQLMap.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying NoSQLMap.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying NoSQLMap.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying NoSQLMap.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/NoSQLMap-0.7-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
zip_safe flag not set; analyzing archive contents...
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing NoSQLMap-0.7-py2.7.egg
Copying NoSQLMap-0.7-py2.7.egg to /usr/local/lib/python2.7/site-packages
Adding NoSQLMap 0.7 to easy-install.pth file
Installing nsmscan.py script to /usr/local/bin
Installing exception.py script to /usr/local/bin
Installing nosqlmap.py script to /usr/local/bin
Installing nsmweb.py script to /usr/local/bin
Installing nsmcouch.py script to /usr/local/bin
Installing nsmmongo.py script to /usr/local/bin
Installing NoSQLMap script to /usr/local/bin

Installed /usr/local/lib/python2.7/site-packages/NoSQLMap-0.7-py2.7.egg
Processing dependencies for NoSQLMap==0.7
Searching for requests==2.20.0
Reading https://pypi.org/simple/requests/
Downloading https://files.pythonhosted.org/packages/f1/ca/10332a30cb25b627192b4ea272c351bce3ca1091e541245cccbace6051d8/requests-2.20.0-py2.py3-none-any.whl#sha256=a84b8c9ab6239b578f22d1c21d51b696dcfe004032bb80ea832398d6909d7279
Best match: requests 2.20.0
Processing requests-2.20.0-py2.py3-none-any.whl
Installing requests-2.20.0-py2.py3-none-any.whl to /usr/local/lib/python2.7/site-packages
Adding requests 2.20.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/site-packages/requests-2.20.0-py2.7.egg
Searching for pymongo==2.7.2
Reading https://pypi.org/simple/pymongo/
Downloading https://files.pythonhosted.org/packages/8e/34/4b3cd4bfe5f3bfbd89873c8e24e091a6a6510c57fedea76161530be18a61/pymongo-2.7.2.tar.gz#sha256=8fb45e3edec006f4b11580fc579bec7781a8b3201ce0abf31593f086070e51f6
Best match: pymongo 2.7.2
Processing pymongo-2.7.2.tar.gz
Writing /tmp/easy_install-HehhLL/pymongo-2.7.2/setup.cfg
Running pymongo-2.7.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-HehhLL/pymongo-2.7.2/egg-dist-tmp-DhWx_W
unable to execute 'gcc': No such file or directory
/tmp/easy_install-HehhLL/pymongo-2.7.2/setup.py:217: UserWarning: 
********************************************************************
WARNING: The bson._cbson extension module could not
be compiled. No C extensions are essential for PyMongo to run,
although they do result in significant speed improvements.
The output above this warning shows how the compilation failed.

Please see the installation docs for solutions to build issues:

http://api.mongodb.org/python/current/installation.html

Here are some hints for popular operating systems:

If you are seeing this message on Linux you probably need to
install GCC and/or the Python development package for your
version of Python.

Debian and Ubuntu users should issue the following command:

    $ sudo apt-get install build-essential python-dev

Users of Red Hat based distributions (RHEL, CentOS, Amazon Linux,
Oracle Linux, Fedora, etc.) should issue the following command:

    $ sudo yum install gcc python-devel

If you are seeing this message on Microsoft Windows please install
PyMongo using the MS Windows installer for your version of Python,
available on pypi here:

http://pypi.python.org/pypi/pymongo/#downloads

If you are seeing this message on OSX please read the documentation
here:

http://api.mongodb.org/python/current/installation.html#osx
********************************************************************

  "The output above "
unable to execute 'gcc': No such file or directory
/tmp/easy_install-HehhLL/pymongo-2.7.2/setup.py:217: UserWarning: 
********************************************************************
WARNING: The pymongo._cmessage extension module could not
be compiled. No C extensions are essential for PyMongo to run,
although they do result in significant speed improvements.
The output above this warning shows how the compilation failed.

Please see the installation docs for solutions to build issues:

http://api.mongodb.org/python/current/installation.html

Here are some hints for popular operating systems:

If you are seeing this message on Linux you probably need to
install GCC and/or the Python development package for your
version of Python.

Debian and Ubuntu users should issue the following command:

    $ sudo apt-get install build-essential python-dev

Users of Red Hat based distributions (RHEL, CentOS, Amazon Linux,
Oracle Linux, Fedora, etc.) should issue the following command:

    $ sudo yum install gcc python-devel

If you are seeing this message on Microsoft Windows please install
PyMongo using the MS Windows installer for your version of Python,
available on pypi here:

http://pypi.python.org/pypi/pymongo/#downloads

If you are seeing this message on OSX please read the documentation
here:

http://api.mongodb.org/python/current/installation.html#osx
********************************************************************

  "The output above "
zip_safe flag not set; analyzing archive contents...
command 'gcc' failed with exit status 1
command 'gcc' failed with exit status 1
Moving pymongo-2.7.2-py2.7-linux-x86_64.egg to /usr/local/lib/python2.7/site-packages
Adding pymongo 2.7.2 to easy-install.pth file

Installed /usr/local/lib/python2.7/site-packages/pymongo-2.7.2-py2.7-linux-x86_64.egg
Searching for pbkdf2==1.3
Reading https://pypi.org/simple/pbkdf2/
Downloading https://files.pythonhosted.org/packages/02/c0/6a2376ae81beb82eda645a091684c0b0becb86b972def7849ea9066e3d5e/pbkdf2-1.3.tar.gz#sha256=ac6397369f128212c43064a2b4878038dab78dab41875364554aaf2a684e6979
Best match: pbkdf2 1.3
Processing pbkdf2-1.3.tar.gz
Writing /tmp/easy_install-QybOTW/pbkdf2-1.3/setup.cfg
Running pbkdf2-1.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-QybOTW/pbkdf2-1.3/egg-dist-tmp-G3RkBQ
zip_safe flag not set; analyzing archive contents...
Moving pbkdf2-1.3-py2.7.egg to /usr/local/lib/python2.7/site-packages
Adding pbkdf2 1.3 to easy-install.pth file

Installed /usr/local/lib/python2.7/site-packages/pbkdf2-1.3-py2.7.egg
Searching for ipcalc==1.1.3
Reading https://pypi.org/simple/ipcalc/
Downloading https://files.pythonhosted.org/packages/15/d7/7d60a28c34d84206f3cd5730405adb57246288e5616100b217d6fe2fef66/ipcalc-1.1.3.tar.gz#sha256=3bfc52cafaa39e9c4e8478a38b21b2d62b2145d3d21a1722f1340e897656ac34
Best match: ipcalc 1.1.3
Processing ipcalc-1.1.3.tar.gz
Writing /tmp/easy_install-MSk36w/ipcalc-1.1.3/setup.cfg
Running ipcalc-1.1.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-MSk36w/ipcalc-1.1.3/egg-dist-tmp-zGRmzQ
zip_safe flag not set; analyzing archive contents...
Moving ipcalc-1.1.3-py2.7.egg to /usr/local/lib/python2.7/site-packages
Adding ipcalc 1.1.3 to easy-install.pth file

Installed /usr/local/lib/python2.7/site-packages/ipcalc-1.1.3-py2.7.egg
Searching for httplib2==0.19.0
Reading https://pypi.org/simple/httplib2/
Downloading https://files.pythonhosted.org/packages/ed/ef/f0e05d5886a9c25dea4b18be06cd7bcaddbae0168cc576f3568f9bd6a35a/httplib2-0.19.0.tar.gz#sha256=e0d428dad43c72dbce7d163b7753ffc7a39c097e6788ef10f4198db69b92f08e
Best match: httplib2 0.19.0
Processing httplib2-0.19.0.tar.gz
Writing /tmp/easy_install-5W_bgQ/httplib2-0.19.0/setup.cfg
Running httplib2-0.19.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-5W_bgQ/httplib2-0.19.0/egg-dist-tmp-kDNwrj
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
zip_safe flag not set; analyzing archive contents...
httplib2.certs: module references __file__
creating /usr/local/lib/python2.7/site-packages/httplib2-0.19.0-py2.7.egg
Extracting httplib2-0.19.0-py2.7.egg to /usr/local/lib/python2.7/site-packages
Adding httplib2 0.19.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/site-packages/httplib2-0.19.0-py2.7.egg
Searching for CouchDB==1.0
Reading https://pypi.org/simple/CouchDB/
Downloading https://files.pythonhosted.org/packages/58/8f/acef7670a97b05200f664982a33a2ae4d78e065b0201d21cd93fc844f21f/CouchDB-1.0-py2.py3-none-any.whl#sha256=a1fe6cab76be7137025785cc5dd7bd37e086c87130d8024783cb59da8aefd9a9
Best match: CouchDB 1.0
Processing CouchDB-1.0-py2.py3-none-any.whl
Installing CouchDB-1.0-py2.py3-none-any.whl to /usr/local/lib/python2.7/site-packages
Adding CouchDB 1.0 to easy-install.pth file
Installing couchdb-dump script to /usr/local/bin
Installing couchpy script to /usr/local/bin
Installing couchdb-load script to /usr/local/bin
Installing couchdb-replicate script to /usr/local/bin

Installed /usr/local/lib/python2.7/site-packages/CouchDB-1.0-py2.7.egg
Searching for urllib3<1.25,>=1.21.1
Reading https://pypi.org/simple/urllib3/
Downloading https://files.pythonhosted.org/packages/01/11/525b02e4acc0c747de8b6ccdab376331597c569c42ea66ab0a1dbd36eca2/urllib3-1.24.3-py2.py3-none-any.whl#sha256=a637e5fae88995b256e3409dc4d52c2e2e0ba32c42a6365fee8bbd2238de3cfb
Best match: urllib3 1.24.3
Processing urllib3-1.24.3-py2.py3-none-any.whl
Installing urllib3-1.24.3-py2.py3-none-any.whl to /usr/local/lib/python2.7/site-packages
Adding urllib3 1.24.3 to easy-install.pth file

Installed /usr/local/lib/python2.7/site-packages/urllib3-1.24.3-py2.7.egg
Searching for idna<2.8,>=2.5
Reading https://pypi.org/simple/idna/
Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl#sha256=156a6814fb5ac1fc6850fb002e0852d56c0c8d2531923a51032d1b70760e186e
Best match: idna 2.7
Processing idna-2.7-py2.py3-none-any.whl
Installing idna-2.7-py2.py3-none-any.whl to /usr/local/lib/python2.7/site-packages
Adding idna 2.7 to easy-install.pth file

Installed /usr/local/lib/python2.7/site-packages/idna-2.7-py2.7.egg
Searching for chardet<3.1.0,>=3.0.2
Reading https://pypi.org/simple/chardet/
Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl#sha256=fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691
Best match: chardet 3.0.4
Processing chardet-3.0.4-py2.py3-none-any.whl
Installing chardet-3.0.4-py2.py3-none-any.whl to /usr/local/lib/python2.7/site-packages
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /usr/local/bin

Installed /usr/local/lib/python2.7/site-packages/chardet-3.0.4-py2.7.egg
Searching for certifi>=2017.4.17
Reading https://pypi.org/simple/certifi/
Downloading https://files.pythonhosted.org/packages/37/f7/2b1b0ec44fdc30a3d31dfebe52226be9ddc40cd6c0f34ffc8923ba423b69/certifi-2022.12.7.tar.gz#sha256=35824b4c3a97115964b408844d64aa14db1cc518f6562e8d7261699d1350a9e3
Best match: certifi 2022.12.7
Processing certifi-2022.12.7.tar.gz
Writing /tmp/easy_install-BLUknw/certifi-2022.12.7/setup.cfg
Running certifi-2022.12.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-BLUknw/certifi-2022.12.7/egg-dist-tmp-Sn98pO
/usr/local/lib/python2.7/site-packages/setuptools/dist.py:476: UserWarning: Normalizing '2022.12.07' to '2022.12.7'
  normalized_version,
warning: no previously-included files found matching '.github/'
warning: manifest_maker: MANIFEST.in, line 4: 'recursive-exclude' expects <dir> <pattern1> <pattern2> ...

  File "build/bdist.linux-x86_64/egg/certifi/core.py", line 17
    def where() -> str:
                ^
SyntaxError: invalid syntax

creating /usr/local/lib/python2.7/site-packages/certifi-2022.12.7-py2.7.egg
Extracting certifi-2022.12.7-py2.7.egg to /usr/local/lib/python2.7/site-packages
  File "/usr/local/lib/python2.7/site-packages/certifi-2022.12.7-py2.7.egg/certifi/core.py", line 17
    def where() -> str:
                ^
SyntaxError: invalid syntax

Adding certifi 2022.12.7 to easy-install.pth file

Installed /usr/local/lib/python2.7/site-packages/certifi-2022.12.7-py2.7.egg
Searching for pyparsing<3,>=2.4.2
Reading https://pypi.org/simple/pyparsing/
Downloading https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl#sha256=ef9d7589ef3c200abe66653d3f1ab1033c3c419ae9b9bdb1240a85b024efc88b
Best match: pyparsing 2.4.7
Processing pyparsing-2.4.7-py2.py3-none-any.whl
Installing pyparsing-2.4.7-py2.py3-none-any.whl to /usr/local/lib/python2.7/site-packages
Adding pyparsing 2.4.7 to easy-install.pth file

Installed /usr/local/lib/python2.7/site-packages/pyparsing-2.4.7-py2.7.egg
Finished processing dependencies for NoSQLMap==0.7
Removing intermediate container c2a5e08e5211
 ---> 9358086271e5
Step 8/10 : COPY entrypoint.sh /tmp/entrypoint.sh
 ---> 3c8456bb005a
Step 9/10 : RUN chmod +x /tmp/entrypoint.sh
 ---> Running in 4544c95f9ad4
Removing intermediate container 4544c95f9ad4
 ---> 8594dd073ad5
Step 10/10 : ENTRYPOINT ["/tmp/entrypoint.sh"]
 ---> Running in 9b3bc41d9027
Removing intermediate container 9b3bc41d9027
 ---> 688f27e64888
Successfully built 688f27e64888
Successfully tagged nosqlmap:latest

```

3. Attempt to run the container from the image:
```
┌──(kali 👿 kali)-[/opt/…/docker]
└─$ sudo docker run -t nosqlmap:latest                                                                   (master|✔)
Traceback (most recent call last):
  File "nosqlmap.py", line 8, in <module>
    import nsmcouch
  File "/root/NoSqlMap/nsmcouch.py", line 8, in <module>
    import requests
  File "/usr/local/lib/python2.7/site-packages/requests-2.20.0-py2.7.egg/requests/__init__.py", line 112, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/site-packages/requests-2.20.0-py2.7.egg/requests/utils.py", line 24, in <module>
    from . import certs
  File "/usr/local/lib/python2.7/site-packages/requests-2.20.0-py2.7.egg/requests/certs.py", line 15, in <module>
    from certifi import where
  File "/usr/local/lib/python2.7/site-packages/certifi-2022.12.7-py2.7.egg/certifi/__init__.py", line 1, in <module>
    from .core import contents, where
  File "/usr/local/lib/python2.7/site-packages/certifi-2022.12.7-py2.7.egg/certifi/core.py", line 17
    def where() -> str:
                ^
SyntaxError: invalid syntax

```

## What are the running context details?

* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`): Docker Build
* Client OS (e.g. `Microsoft Windows 10`): Kali

**Comment by BKreisel** [comment]
Looks like the certifi package recently added type hints which won't work on python2 (they haven't advertised 2 support for a few years no). Requests 2.20.0 is pulling it in as a sub-dependency.
