### ISSUE TITLE
Error responses from web attack crash program

### ISSUE THREAD

**Issue by darinrogers** [codingo/NoSQLMap#32]
If a call returns an error status code (e.g. 422, which is a valid response in my app as it tells the browser that the call didn't succeed and to show an error to the user), the program crashes. The stack trace looks like this:

Sending random parameter value...
Traceback (most recent call last):
  File "/usr/local/bin/NoSQLMap", line 9, in <module>
    load_entry_point('NoSQLMap==0.5', 'console_scripts', 'NoSQLMap')()
  File "/usr/local/lib/python2.7/dist-packages/NoSQLMap-0.5-py2.7.egg/EGG-INFO/scripts/nosqlmap.py", line 60, in main

  File "/usr/local/lib/python2.7/dist-packages/NoSQLMap-0.5-py2.7.egg/EGG-INFO/scripts/nosqlmap.py", line 115, in mainMenu

  File "/usr/local/lib/python2.7/dist-packages/NoSQLMap-0.5-py2.7.egg/EGG-INFO/scripts/nosqlmap.py", line 534, in postApps

  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 422: Unprocessable Entity

**Comment by tcstool** [comment]
Good catch. I am rewriting the web request handling as part of issue 31.  I
will include a fix for this.  Thanks!

**Comment by odinn1984** [comment]
@tcstool any update here?

**Comment by tcstool** [comment]
Project has a new maintainer now, this should be fixed shortly.

**Comment by codingo** [comment]
Hi @darinrogers @odinn1984, as @tcstool mentioned I came on board yesterday. At the moment I'm looking for a design patters and doing some minor refactoring to learn my way around every part of the project. As a part of that I will be re-writing the HTTP module and I'll touch base in this thread as that work lands. Shouldn't be much longer!

**Comment by codingo** [comment]
Closed with #61
