### ISSUE TITLE
Can I use this to test “Express” framework?

### ISSUE THREAD

**Issue by pws019** [codingo/NoSQLMap#52]
when I  try It says:

```shell
Sending random parameter value...
Got response length of 63.
Random value variance: 119071

Test 1: PHP/ExpressJS != associative array injection
Injection failed.


Test 2: $where injection (string escape)
Traceback (most recent call last):
  File "./nosqlmap.py", line 469, in <module>
    main()
  File "./nosqlmap.py", line 51, in main
    mainMenu()
  File "./nosqlmap.py", line 109, in mainMenu
    nsmweb.getApps(webPort,victim,uri,https,verb,requestHeaders)
  File "/home/pws019/Desktop/software/NoSQLMap/nsmweb.py", line 146, in getApps
    errorCheck = errorTest(str(urllib2.urlopen(req).read()),testNum)
  File "/usr/local/python3/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/python3/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/python3/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/python3/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/python3/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/python3/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/python3/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/local/python3/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python3/lib/python2.7/httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
```

**Comment by tcstool** [comment]
That seems like an error in the way the web app is handling the request itself.  Can you try it manually and let me see the output so I can add handling?

**Comment by codingo** [comment]
@pws019 just touching base to see where you've landed with this one?

**Comment by codingo** [comment]
Closing this as nothing further. Feel free to reply back if you require this to be reopened.
