### ISSUE TITLE
TypeError: range() integer end argument expected, got str.

### ISSUE THREAD

**Issue by ahasanaki** [codingo/NoSQLMap#75]
Hello;
I Set Options Using Burp request and when i wanna using web app attack(mongo and node.js web app) I encounter an error
-------------------------------------------------------------------------------------------------------------------
....
List of parameters:
1-password
2-email
Which parameter should we inject? 1
Injecting the password parameter...
Baseline test-Enter random string size: 10
What format should the random string take?
1-Alphanumeric
2-Letters only
3-Numbers only
4-Email address
Select an option: 1
Traceback (most recent call last):
  File "/usr/local/bin/nosqlmap.py", line 4, in <module>
    __import__('pkg_resources').run_script('NoSQLMap==0.7', 'nosqlmap.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1451, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/NoSQLMap-0.7-py2.7.egg/EGG-INFO/scripts/nosqlmap.py", line 534, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/NoSQLMap-0.7-py2.7.egg/EGG-INFO/scripts/nosqlmap.py", line 46, in main
    
  File "/usr/local/lib/python2.7/dist-packages/NoSQLMap-0.7-py2.7.egg/EGG-INFO/scripts/nosqlmap.py", line 102, in mainMenu
    
  File "/usr/local/lib/python2.7/dist-packages/NoSQLMap-0.7-py2.7.egg/EGG-INFO/scripts/nsmweb.py", line 486, in postApps
    
  File "/usr/local/lib/python2.7/dist-packages/NoSQLMap-0.7-py2.7.egg/EGG-INFO/scripts/nsmweb.py", line 885, in build_random_string
    
TypeError: range() integer end argument expected, got str.

**Comment by alexdetrano** [comment]
I submitted a PR for this: https://github.com/codingo/NoSQLMap/pull/81

**Comment by codingo** [comment]
Closed with #81
