### ISSUE TITLE
setup.py: broken install

### ISSUE THREAD

**Issue by blshkv** [codingo/NoSQLMap#90]
Clone the latest version:
```
git clone https://github.com/codingo/NoSQLMap.git 
```

install it:
```
python setup.py install --user
```

Run:
```
bash$ python2 ~/.local/bin/NoSQLMap 

Traceback (most recent call last):
  File "./NoSQLMap", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'NoSQLMap==0.7' distribution was not found and is required by the application
```

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/issues/596

**Comment by blshkv** [comment]
Please re-open if you care. This issue is NOT fixed.
